import * as dotenvSafe from 'dotenv-safe';
import { z } from 'zod';

dotenvSafe.config({ example: '.env.example', allowEmptyValues: true });

const envSchema = z.object({
  API_BASE_URL: z.string().min(1),
  API_PORT: z.coerce.number(),
  ENV: z.string().optional().default('development'),
  LOG_LEVEL: z.string().optional().default('info'),
  REDIS_URL: z.string().optional().default('redis://127.0.0.1:6379'),
  MONGODB_URI: z.string().min(1),
  MONGODB_DATABASE_NAME: z.string().min(1),
  CORS_ORIGINS: z.string().optional().default(''),
  JWT_SECRET: z.string().optional().default('dev-secret'),
  OCR_BASE_URL: z.string().optional().default('http://127.0.0.1:8000'),
  OCR_API_KEY: z.string().min(1),
  RATE_LIMIT_WINDOW_MS: z.coerce.number().optional().default(60_000),
  RATE_LIMIT_PUBLIC_MAX: z.coerce.number().optional().default(10),
  RATE_LIMIT_PUBLIC_HOURLY_MAX: z.coerce.number().optional().default(200),
  RATE_LIMIT_GLOBAL_MAX: z.coerce.number().optional().default(60),
  RATE_LIMIT_LLM_MAX: z.coerce.number().optional().default(5),
  BULK_WORKER_CONCURRENCY: z.coerce.number().optional().default(1),
  LLM_WORKER_CONCURRENCY: z.coerce.number().optional().default(1),
  SSE_POLL_INTERVAL_MS: z.coerce.number().optional().default(3000),
  SSE_KEEPALIVE_INTERVAL_MS: z.coerce.number().optional().default(15000),
  ANTHROPIC_API_KEY: z.string().optional(),
  ANTHROPIC_MODEL: z.string().optional(),
  ANTHROPIC_FALLBACK_MODEL: z.string().optional(),
  OPENAI_API_KEY: z.string().optional(),
});

export const env = envSchema.parse({
  API_BASE_URL: process.env.API_BASE_URL,
  API_PORT: process.env.API_PORT,
  ENV: process.env.ENV,
  LOG_LEVEL: process.env.LOG_LEVEL,
  REDIS_URL: process.env.REDIS_URL,
  MONGODB_URI: process.env.MONGODB_URI,
  MONGODB_DATABASE_NAME: process.env.MONGODB_DATABASE_NAME,
  CORS_ORIGINS: process.env.CORS_ORIGINS,
  JWT_SECRET: process.env.JWT_SECRET,
  OCR_BASE_URL: process.env.OCR_BASE_URL,
  OCR_API_KEY: process.env.OCR_API_KEY,
  RATE_LIMIT_WINDOW_MS: process.env.RATE_LIMIT_WINDOW_MS,
  RATE_LIMIT_PUBLIC_MAX: process.env.RATE_LIMIT_PUBLIC_MAX,
  RATE_LIMIT_PUBLIC_HOURLY_MAX: process.env.RATE_LIMIT_PUBLIC_HOURLY_MAX,
  RATE_LIMIT_GLOBAL_MAX: process.env.RATE_LIMIT_GLOBAL_MAX,
  RATE_LIMIT_LLM_MAX: process.env.RATE_LIMIT_LLM_MAX,
  BULK_WORKER_CONCURRENCY: process.env.BULK_WORKER_CONCURRENCY,
  LLM_WORKER_CONCURRENCY: process.env.LLM_WORKER_CONCURRENCY,
  SSE_POLL_INTERVAL_MS: process.env.SSE_POLL_INTERVAL_MS,
  SSE_KEEPALIVE_INTERVAL_MS: process.env.SSE_KEEPALIVE_INTERVAL_MS,
  ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
  ANTHROPIC_MODEL: process.env.ANTHROPIC_MODEL,
  ANTHROPIC_FALLBACK_MODEL: process.env.ANTHROPIC_FALLBACK_MODEL,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
});
